---
# Forward authentication to Uitsmijter Public
# usage:
#   traefik.ingress.kubernetes.io/router.middlewares: sso-forward-header@kubernetescrd

apiVersion: {{ .Values.traefik.apiVersion | default "traefik.io/v1alpha1" }}
kind: Middleware
metadata:
  namespace: {{ include "uitsmijter.namespace" . }}
  name: forward-header
spec:
  headers:
    customRequestHeaders:
      "X-Uitsmijter-Mode": "interceptor"
